# Generated by Django 3.2.4 on 2021-07-18 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_article_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
