# Generated by Django 3.2.4 on 2021-07-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20210718_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Title',
            field=models.CharField(max_length=100),
        ),
    ]
